export { default as Login } from './login/Login';
export {default as Register} from './register/Register'
export {default as Dashboard} from './dashboard/Dashboard'
export {default as Frontpage} from './frontpage/Frontpage'
export {default as Theater} from './theater/Theater'
export {default as AdminMovies} from './movie/AdminMovies'
export{default as UserMovies} from './movie/UserMovies'
export {default as MovieDetails} from './movie/MovieDetails'
export {default as Bookings} from './bookings/Bookings'
export {default as UserBooking} from './bookings/UserBooking'
export {default as Report} from './reports/Report'
export {default as Analytics} from './analytics/Analytics'